baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "deadhand"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2