baseURL = "https://deadhandmedia.com/"
languageCode = "en-us"
title = "DeadHand Media"
theme = "deadhand"

disableKinds = ["categories", "tags"]

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2
