baseURL = "http://example.org/"
languageCode = "en-us"
title = "DeadHand Media"
theme = "deadhand"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2
