baseURL = "https://deadhandmedia.com/"
languageCode = "en-us"
title = "Tyler Smith"
enableInlineShortcodes = true
disableKinds = ["RSS"]
googleAnalytics = 'UA-100417057-1'

[caches]
  [caches.getjson]
    dir = ':resourceDir/cache/'
    maxAge = "10m"

[taxonomies]

[menu]
   [[menu.main]]
     name = "About"
     url = "/about/"
     weight = 1

   [[menu.main]]
     name = "Blog"
     url = "/blog/"
     weight = 2

   [[menu.main]]
     name = "Projects"
     url = "/projects/"
     weight = 3

   [[menu.main]]
     name = "Resume"
     url = "/resume/"
     weight = 4

[security]
  [security.funcs]
    getenv = ['^HUGO_', 'PWD']