baseURL = "https://deadhandmedia.com/"
languageCode = "en-us"
title = "DeadHand Media"
enableInlineShortcodes = true
disableKinds = ["RSS"]

[taxonomies]

[menu]

   [[menu.main]]
     name = "Projects"
     url = "/projects/"
     weight = 2

   [[menu.main]]
     name = "Resume"
     url = "/resume/"
     weight = 2

