# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "DeadHand"
description = "Theme for DeadHand Media Site"
homepage = "http://deadhandmedia.com/"

[author]
  name = "Tyler Smith"
  homepage = "http://deadhandmedia.com/"
