name: Trigger Netlify Build
on: push

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Curl request
        shell: bash
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: curl -X POST -d {} "$NETLIFY_BUILD_HOOK"
